# Generated by Django 3.2.7 on 2021-09-27 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("topic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmodel",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.user"
            ),
        ),
        migrations.AlterField(
            model_name="topicmodel",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authentication.user"
            ),
        ),
    ]
