# Generated by Django 3.2.7 on 2021-09-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0002_auto_20210927_2226"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicmodel",
            name="content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
