# Generated by Django 3.2.7 on 2021-09-29 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_alter_postmodel_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
