# Generated by Django 3.2.7 on 2021-09-29 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0005_auto_20210929_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
